### ISSUE TITLE
Difference between fedora-toolbox

### ISSUE THREAD

**Issue by fabriciomj** [ublue-os/fedora-distrobox#5]
Hello, what difference does this container image provide from what you get from the regular fedora-toolbox and why is it needed?

**Comment by bigpod98** [comment]
This one has additions so it can also be used with distrobox, a more customizable alternative to toolbox

**Comment by fabriciomj** [comment]
Can't the fedora-toolbox image also be used in distrobox?

**Comment by bigpod98** [comment]
While yes it can, this image includes additional paclages that provide better oit of the box experiance, like almost instant first enter and such.

Almost any oci image that has a traditional linux package manager can be used with distrobox as distrobox can leverage traditionsl packagr manager to provided needed packages which can take minute or two, while this image already brings those needed packages which decreases first launch time to near instant

**Comment by bigpod98** [comment]
While yes it can, this image includes additional paclages that provide better oit of the box experiance, like almost instant first enter and such.

Almost any oci image that has a traditional linux package manager can be used with distrobox as distrobox can leverage traditionsl packagr manager to provided needed packages which can take minute or two, while this image already brings those needed packages which decreases first launch time to near instant

**Comment by fabriciomj** [comment]
I see. I got confused when I was reading the file `30-distrobox.just` from the `ublue-os/config` repo and the fedora, arch and (obviously) bazzite images were from the uBlue project. After reading the `arch-distrobox` repo, though, I better understood what the `xdg-utils` is for. Thanks for the help, I'm closing this issue.
